"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { motion } from "framer-motion";
import Link from "next/link";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { LoadingAnimation } from "@/components/LoadingAnimation";
import { SongPlayer } from "@/components/SongPlayer";
import { FaPlay } from "react-icons/fa";

interface Song {
  id: string;
  title: string;
  previewUrl: string;
  style: string;
  story: string;
}

export default function SharePage() {
  const params = useParams();
  const songId = params.id as string;
  
  const [song, setSong] = useState<Song | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (songId) {
      fetchSong(songId);
    }
  }, [songId]);

  const fetchSong = async (id: string) => {
    try {
      const response = await fetch(`/api/song/${id}`);
      const data = await response.json();
      
      if (data.success) {
        setSong(data.song);
      }
    } catch (error) {
      console.error("Error fetching song:", error);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <LoadingAnimation message="Loading song..." />
      </div>
    );
  }

  if (!song) {
    return (
      <div className="min-h-screen">
        <Header />
        <main className="pt-32 pb-20">
          <div className="max-w-3xl mx-auto px-4 text-center">
            <h1 className="text-3xl font-bold text-gray-900 mb-4">
              Song not found
            </h1>
            <p className="text-gray-600 mb-8">
              This song may have been deleted or the link is invalid.
            </p>
            <Link href="/story">
              <button className="btn-primary">Create Your Own Song</button>
            </Link>
          </div>
        </main>
        <Footer />
      </div>
    );
  }

  return (
    <div className="min-h-screen">
      <Header />
      
      <main className="pt-32 pb-20">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="space-y-8"
          >
            <div className="text-center space-y-4">
              <motion.div
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                transition={{ delay: 0.2, type: "spring" }}
              >
                <div className="text-6xl mb-4">🎵💔</div>
              </motion.div>
              <h1 className="text-4xl md:text-5xl font-bold text-gray-900">
                {song.title}
              </h1>
              <p className="text-xl text-gray-600">
                A breakup song generated by AI
              </p>
            </div>

            <SongPlayer
              audioUrl={song.previewUrl}
              title={song.title}
              isPreview={true}
              previewDuration={10}
            />
            
            <div className="card bg-gradient-to-br from-heartbreak-50 to-heartbreak-100 border-2 border-heartbreak-200">
              <div className="text-center space-y-4">
                <div className="flex items-center justify-center space-x-3">
                  <FaPlay className="text-3xl text-heartbreak-500" />
                  <p className="text-lg text-gray-700">
                    This is a 10-second preview. Create your own to unlock the full song!
                  </p>
                </div>
              </div>
            </div>

            <div className="card">
              <h3 className="text-xl font-bold text-gray-900 mb-4">
                The Story Behind the Song
              </h3>
              <p className="text-gray-700 italic mb-4">"{song.story}"</p>
              <div className="flex items-center space-x-2">
                <span className="px-3 py-1 bg-healing-200 text-healing-800 rounded-full text-sm font-medium">
                  {song.style.charAt(0).toUpperCase() + song.style.slice(1)} Vibe
                </span>
              </div>
            </div>

            <div className="text-center">
              <Link href="/story">
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  className="btn-primary"
                >
                  Create Your Own Breakup Song
                </motion.button>
              </Link>
            </div>
          </motion.div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
